### PR TITLE
MNT Pushing data up instead of indices

### PR DESCRIPTION
**Pull request by thomasjpfan**
Related to https://github.com/jjerphan/scikit-learn/pull/15#discussion_r943093271 and an alternative to using a pointer to invalid memory.

I have not benchmark this implementation, but I suspect it should perform the same.

### CODE REVIEW

**Review by jjerphan — APPROVED** [review]
Ah yes, that's definitely simpler and better (no potential false sharing at all). Thank you, @thomasjpfan!

**Comment by jjerphan** [comment]
I would just revert the signatures to use memoryviews instead of pointers for `indices` arrays now that the offset is performed on `data` arrays.

**Comment by thomasjpfan** [comment]
I reverted back to memoryviews in [`3086c0b` (#16)](https://github.com/jjerphan/scikit-learn/pull/16/commits/3086c0b492bff75f15c126eac7f3cea22ed9a8bf)

> We can also drop the synthetic indptr array in SparseDenseDatasetsPair.

Can you finish this up in https://github.com/jjerphan/scikit-learn/pull/15? I do not see how to drop the synthetic arrays.

**Comment by jjerphan** [comment]
My bad, I thought we were still using one extra `indptr`, but that's not the case.

**Pull request merged**
